# Generated by Django 5.1.12 on 2025-12-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
