# Generated by Django 5.2.9 on 2025-12-24 06:17

import api.user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_user", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", api.user.models.CustomUserManager()),
            ],
        ),
    ]
