# Generated by Django 5.2.9 on 2026-02-18 17:24

import api.room.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="end_datetime",
            field=models.DateTimeField(default=api.room.models.get_end_of_today),
        ),
        migrations.AlterField(
            model_name="room",
            name="recurrence_rule",
            field=models.CharField(blank=True, default="FREQ=DAILY", max_length=64),
        ),
        migrations.AlterField(
            model_name="room",
            name="start_datetime",
            field=models.DateTimeField(default=api.room.models.get_start_of_today),
        ),
    ]
