# Generated by Django 5.1.12 on 2025-12-03 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_alter_room_created_at_alter_room_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenties",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="amenties",
            field=models.ManyToManyField(blank=True, to="room.amenties"),
        ),
        migrations.AlterField(
            model_name="room",
            name="location_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="room.location"
            ),
        ),
    ]
