# Generated by Django 5.2.9 on 2025-12-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_alter_room_capacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="room_images/"),
        ),
    ]
