# Generated by Django 5.2.9 on 2025-12-10 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_alter_room_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="room.location"
            ),
        ),
    ]
