# Generated by Django 5.1.12 on 2025-12-03 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0003_amenties_location_room_amenties_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capacity",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name="room",
            name="capacity_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="room.capacity"
            ),
        ),
    ]
