# Generated by Django 5.2.9 on 2025-12-11 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_alter_room_location"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenities",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"ordering": ["id"]},
        ),
    ]
