# Generated by Django 5.1.12 on 2025-12-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0004_capacity_alter_room_capacity_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="amenties",
            new_name="amenities",
        ),
    ]
