# Generated by Django 5.1.12 on 2025-12-06 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0005_rename_amenties_room_amenities"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="capacity_id",
            new_name="capacity",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="location_id",
            new_name="location",
        ),
        migrations.RemoveField(
            model_name="room",
            name="img_url",
        ),
        migrations.AddField(
            model_name="room",
            name="img",
            field=models.ImageField(default=2, upload_to=""),
            preserve_default=False,
        ),
    ]
