# Generated by Django 5.2.9 on 2025-12-11 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0005_alter_amenities_options_alter_location_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Amenities",
            new_name="Amenity",
        ),
    ]
