# Generated by Django 5.1.12 on 2025-12-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0006_rename_capacity_id_room_capacity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="capacity",
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name="room",
            name="status",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="Capacity",
        ),
    ]
