# Generated by Django 5.1.12 on 2025-11-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("visiter_name", models.CharField(max_length=100)),
                ("visiter_email", models.CharField(max_length=100)),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("recurrence_rule", models.CharField(blank=True, verbose_name=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CONFIRMED", "CONFIRMED"),
                            ("CANCELLED", "CANCELLED"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        max_length=9,
                    ),
                ),
                ("google_event_id", models.IntegerField()),
                ("cancel_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="room.room"
                    ),
                ),
            ],
        ),
    ]
