# Generated by Django 5.1.12 on 2025-11-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="google_event_id",
            field=models.CharField(max_length=100),
        ),
    ]
