# Generated by Django 5.2.9 on 2025-12-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("CONFIRMED", "CONFIRMED"),
                    ("CANCELLED", "CANCELLED"),
                    ("COMPLETED", "COMPLETED"),
                ],
                default="CONFIRMED",
                max_length=9,
            ),
        ),
    ]
