# Generated by Django 5.2.9 on 2025-12-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
