# Generated by Django 5.2.9 on 2025-12-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="visitor_email",
            field=models.EmailField(max_length=100),
        ),
    ]
