# Generated by Django 5.1.12 on 2025-11-25 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_google_event_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="visiter_email",
            new_name="visitor_email",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="visiter_name",
            new_name="visitor_name",
        ),
    ]
