# Generated by Django 5.2.9 on 2025-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_alter_booking_google_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="google_event_id",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
