# Generated by Django 5.1.12 on 2025-11-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_visiter_email_booking_visitor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='recurrence_rule',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
