# Generated by Django 5.2.9 on 2026-02-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_alter_booking_visitor_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="actual_end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
