# Generated by Django 5.2.8 on 2025-12-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_rename_visiter_email_booking_visitor_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="google_event_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="booking",
            name="recurrence_rule",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
